allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  esbuild: true
  onnxruntime-node: true
  prisma: true
  protobufjs: true
  sharp: true
  sqlite3: true
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  '@mikro-orm/knex@<=6.6.13': '>=6.6.14'
  '@tootallnate/once@<3.0.1': '>=3.0.1'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  fast-uri@<=3.1.0: '>=3.1.1'
  fast-uri@<=3.1.1: '>=3.1.2'
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-builder@=1.1.5: '>=1.1.6'
  hono@<4.12.18: '>=4.12.18'
  ip-address@<=10.1.0: '>=10.1.1'
  protobufjs@<=7.5.7: '>=7.5.8'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tar@<=7.5.9: '>=7.5.10'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
